#
# Makefile for CSSE 132 Exam 2
#

# IMPORTANT: all lines after each rule must start with a tab (not spaces)
part1: part1.c
	gcc -g -o part1 part1.c

shuffle: shuffle.c
	gcc -g -o shuffle shuffle.c

